### ISSUE TITLE
help with error

### ISSUE THREAD

**Issue by crisc2000** [SK-Hardwired/nv_hevc_hdr_patcher#11]
I have a mkv file that have problems with rendering correct on my Samsung Tv.
The image has to much contrast, to many darks and highlights.
I have open the mkv file and found this parameters with mediainfo https://mediaarea.net/en/MediaInfo :

> Mastering display color primar : R: x=0.680000 y=0.320000, G: x=0.265000 y=0.690000, B: x=0.150000 y=0.060000, White point: x=0.312700 y=0.329000
> Mastering display luminance    : min: 0.0050 cd/m2, max: 4000.0000 cd/m2

text mode

> 0000006CF    option:                              master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)
> 000000724    option:                              max-cll=0,0
> 000000730    option:                              min-luma=0
> 00000073B    option:                              max-luma=1023

so i extracted the video stream with this tool https://sourceforge.net/projects/gmkvextractgui/files/v2.2.0/
and tried to overwrite masterdisplay data with your software. I got some errors:
```

c:\a>nvhsp.exe -masterdisplay G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) "valerian.h265" "valerian_new.h265"
Parsing the infile:

==========================

Prepending SEI data
Starting new SEI NALu...
SEI message Mastering Display Data G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) created in SEI NAL
Looking for SPS......... [232, 11555224]
SPS_Nals_addresses [232, 11555224]
SPS NAL Size 848
Starting reading SPS NAL contents
Traceback (most recent call last):
  File "site-packages\bitstring.py", line 2012, in _readtoken
TypeError: _readue() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\bitstring.py", line 896, in __getitem__
AttributeError: 'int' object has no attribute 'step'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\bitstring.py", line 1649, in _readue
  File "site-packages\bitstring.py", line 902, in __getitem__
IndexError: Slice index out of range.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nvhsp.py", line 684, in <module>
  File "nvhsp.py", line 418, in main
  File "nvhsp.py", line 418, in <listcomp>
  File "site-packages\bitstring.py", line 3896, in read
  File "site-packages\bitstring.py", line 2020, in _readtoken
  File "site-packages\bitstring.py", line 1652, in _readue
bitstring.ReadError: Read off end of bitstring trying to read code.
Failed to execute script nvhsp
```

**Comment by Majibear** [comment]
I'm facing the exact same error. Did you ever resolve this issue?
